# Generated by Django 4.2.9 on 2024-01-30 08:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Город размещения"),
                ),
                ("created_date", models.DateField(verbose_name="Дата основания")),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Программист"),
                            (1, "Журналист"),
                            (2, "Менеджер"),
                            (3, "Дизайнер"),
                            (4, "Стажер"),
                        ],
                        default=4,
                        verbose_name="Должность",
                    ),
                ),
                ("salary", models.IntegerField(verbose_name="Зарплата")),
                ("hire_date", models.DateField(verbose_name="Дата приема на работу")),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "tasks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Задачи",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.department",
                        verbose_name="Департамент",
                    ),
                ),
            ],
        ),
    ]
