# Generated by Django 4.2.9 on 2024-01-30 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employees",
            new_name="Employee",
        ),
    ]
